name: Run Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Tests
      run: pip install -r requirements-test.txt
    - name: Install Module
      run: pip install .
    - name: Run Tests
      run: python -m pytest --cov=pyavro